apiVersion: v1
kind: Service
metadata:
  name: stockprovidersvc
  labels:
    app: stockprovidersvc
spec:
  ports:
  - port: 33001
    targetPort: 33001
    protocol: TCP
  selector:
    app: stockprovider
